# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: consensus.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'consensus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onsensus.proto\x12\tconsensus\"s\n\x0eVectorClockMap\x12\x33\n\x05\x63lock\x18\x01 \x03(\x0b\x32$.consensus.VectorClockMap.ClockEntry\x1a,\n\nClockEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x91\x01\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\x12/\n\x0cvector_clock\x18\x05 \x01(\x0b\x32\x19.consensus.VectorClockMap\"c\n\x0cVoteResponse\x12\x14\n\x0cvote_granted\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12/\n\x0cvector_clock\x18\x03 \x01(\x0b\x32\x19.consensus.VectorClockMap\"\xd4\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12$\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x13.consensus.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\x12/\n\x0cvector_clock\x18\x07 \x01(\x0b\x32\x19.consensus.VectorClockMap\"g\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12/\n\x0cvector_clock\x18\x03 \x01(\x0b\x32\x19.consensus.VectorClockMap\"~\n\x08LogEntry\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12.\n\x0bvector_time\x18\x05 \x01(\x0b\x32\x19.consensus.VectorClockMap2\xa6\x01\n\x10\x43onsensusService\x12>\n\x0bRequestVote\x12\x16.consensus.VoteRequest\x1a\x17.consensus.VoteResponse\x12R\n\rAppendEntries\x12\x1f.consensus.AppendEntriesRequest\x1a .consensus.AppendEntriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consensus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTORCLOCKMAP_CLOCKENTRY']._loaded_options = None
  _globals['_VECTORCLOCKMAP_CLOCKENTRY']._serialized_options = b'8\001'
  _globals['_VECTORCLOCKMAP']._serialized_start=30
  _globals['_VECTORCLOCKMAP']._serialized_end=145
  _globals['_VECTORCLOCKMAP_CLOCKENTRY']._serialized_start=101
  _globals['_VECTORCLOCKMAP_CLOCKENTRY']._serialized_end=145
  _globals['_VOTEREQUEST']._serialized_start=148
  _globals['_VOTEREQUEST']._serialized_end=293
  _globals['_VOTERESPONSE']._serialized_start=295
  _globals['_VOTERESPONSE']._serialized_end=394
  _globals['_APPENDENTRIESREQUEST']._serialized_start=397
  _globals['_APPENDENTRIESREQUEST']._serialized_end=609
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=611
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=714
  _globals['_LOGENTRY']._serialized_start=716
  _globals['_LOGENTRY']._serialized_end=842
  _globals['_CONSENSUSSERVICE']._serialized_start=845
  _globals['_CONSENSUSSERVICE']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
