# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/consensus.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto/consensus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/consensus.proto\x12\tconsensus\"`\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"2\n\x0cVoteResponse\x12\x14\n\x0cvote_granted\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\"\xa3\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12$\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x13.consensus.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"N\n\x08LogEntry\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t2\xa6\x01\n\x10\x43onsensusService\x12>\n\x0bRequestVote\x12\x16.consensus.VoteRequest\x1a\x17.consensus.VoteResponse\x12R\n\rAppendEntries\x12\x1f.consensus.AppendEntriesRequest\x1a .consensus.AppendEntriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.consensus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=36
  _globals['_VOTEREQUEST']._serialized_end=132
  _globals['_VOTERESPONSE']._serialized_start=134
  _globals['_VOTERESPONSE']._serialized_end=184
  _globals['_APPENDENTRIESREQUEST']._serialized_start=187
  _globals['_APPENDENTRIESREQUEST']._serialized_end=350
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=352
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=406
  _globals['_LOGENTRY']._serialized_start=408
  _globals['_LOGENTRY']._serialized_end=486
  _globals['_CONSENSUSSERVICE']._serialized_start=489
  _globals['_CONSENSUSSERVICE']._serialized_end=655
# @@protoc_insertion_point(module_scope)
