# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"1\n\x0ePaymentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"E\n\x0fPaymentResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"!\n\x0eHistoryRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"=\n\x0fHistoryResponse\x12*\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x14.payment.Transaction\"Q\n\x0bTransaction\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t2\x96\x01\n\x0ePaymentService\x12\x43\n\x0eProcessPayment\x12\x17.payment.PaymentRequest\x1a\x18.payment.PaymentResponse\x12?\n\nGetHistory\x12\x17.payment.HistoryRequest\x1a\x18.payment.HistoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTREQUEST']._serialized_start=26
  _globals['_PAYMENTREQUEST']._serialized_end=75
  _globals['_PAYMENTRESPONSE']._serialized_start=77
  _globals['_PAYMENTRESPONSE']._serialized_end=146
  _globals['_HISTORYREQUEST']._serialized_start=148
  _globals['_HISTORYREQUEST']._serialized_end=181
  _globals['_HISTORYRESPONSE']._serialized_start=183
  _globals['_HISTORYRESPONSE']._serialized_end=244
  _globals['_TRANSACTION']._serialized_start=246
  _globals['_TRANSACTION']._serialized_end=327
  _globals['_PAYMENTSERVICE']._serialized_start=330
  _globals['_PAYMENTSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
