# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import payment_pb2 as payment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x0breplication\x1a\rpayment.proto\"U\n\x12ReplicationRequest\x12*\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x14.payment.Transaction\x12\x13\n\x0bsource_node\x18\x02 \x01(\t\"6\n\x13ReplicationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2j\n\x12ReplicationService\x12T\n\x0fReplicateLedger\x12\x1f.replication.ReplicationRequest\x1a .replication.ReplicationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPLICATIONREQUEST']._serialized_start=49
  _globals['_REPLICATIONREQUEST']._serialized_end=134
  _globals['_REPLICATIONRESPONSE']._serialized_start=136
  _globals['_REPLICATIONRESPONSE']._serialized_end=190
  _globals['_REPLICATIONSERVICE']._serialized_start=192
  _globals['_REPLICATIONSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
